version: "3"
services: 
  server:
    build: 
      context: ./server
      target: development
    container_name: server_c
    ports: 
      - '3001:3001'
    volumes:
      - ./server:/app
      - /app/node_modules
    links: 
      - mongo
    command: npm run dev
  client: 
    build: 
      context: ./client
    container_name: client_c
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    stdin_open: true
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - '27017:27017'